# .github/workflows/python-app.yml

name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        coverage run -m unittest discover -s tests
        coverage xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Asianfleet/catenaconf
        name: codecov-catenaconf-test
        fail_ci_if_error: true